development:
  adapter: postgresql
  encoding: unicode
  database: crud_development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: crud_test
  pool: 5
  username: postgres
  password:
  host: localhost